### ISSUE TITLE
Enquiry about dataset

### ISSUE THREAD

**Issue by Hyeokreal** [musikisomorphie/swd#2]
Hi, many thanks for you to sharing this cool repository.

I have a question about a dataset.
I have no idea of how can I get Trailer Faces dataset.

Can I know how can I download the Trailer Faces dataset?

**Comment by musikisomorphie** [comment]
Hi, thank you for your email. We are still in the discussion in terms of this dataset release.
Hopefully, the download link will be available in the next few weeks.

**Comment by zhiwu-huang** [comment]
Hi, we tentatively release the tfrecord data at https://github.com/musikisomorphie/swd/blob/master/README.md to avoid the copyright issue.
