### ISSUE TITLE
Papers supplementary material missing

### ISSUE THREAD

**Issue by ariel415el** [musikisomorphie/swd#4]
Hi,

Can you provide a new link/ fix the existing link for the supplementary material of your paper?
The Link from [CVPR 2019](https://openaccess.thecvf.com/content_CVPR_2019/supplemental/Wu_Sliced_Wasserstein_Generative_CVPR_2019_supplemental.pdf)
does not work anymore

**Comment by musikisomorphie** [comment]
Hi, I found the supplementary material. Please check the link 
https://drive.google.com/file/d/1XQGhe0_lK4DegDZNRBWbMg7-FCdoZ4cD/view?usp=sharing
